// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ApartmentApps.Client;
using ApartmentApps.Client.Models;
using Microsoft.Rest;

namespace ApartmentApps.Client
{
    public static partial class ConfigureExtensions
    {
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        /// <param name='qrCode'>
        /// Required.
        /// </param>
        /// <param name='latitude'>
        /// Required.
        /// </param>
        /// <param name='longitude'>
        /// Required.
        /// </param>
        /// <param name='label'>
        /// Optional.
        /// </param>
        public static object AddLocation(this IConfigure operations, string qrCode, double latitude, double longitude, string label = null)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IConfigure)s).AddLocationAsync(qrCode, latitude, longitude, label);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        /// <param name='qrCode'>
        /// Required.
        /// </param>
        /// <param name='latitude'>
        /// Required.
        /// </param>
        /// <param name='longitude'>
        /// Required.
        /// </param>
        /// <param name='label'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> AddLocationAsync(this IConfigure operations, string qrCode, double latitude, double longitude, string label = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.AddLocationWithOperationResponseAsync(qrCode, latitude, longitude, label, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='type'>
        /// Required.
        /// </param>
        public static object DeleteLocation(this IConfigure operations, int id, string type)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IConfigure)s).DeleteLocationAsync(id, type);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='type'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<object> DeleteLocationAsync(this IConfigure operations, int id, string type, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<object> result = await operations.DeleteLocationWithOperationResponseAsync(id, type, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        public static IList<LocationBindingModel> GetLocations(this IConfigure operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IConfigure)s).GetLocationsAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ApartmentApps.Client.IConfigure.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<LocationBindingModel>> GetLocationsAsync(this IConfigure operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<ApartmentApps.Client.Models.LocationBindingModel>> result = await operations.GetLocationsWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
