// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;

namespace ApartmentApps.Client
{
    public partial interface INotifiations
    {
        /// <param name='pns'>
        /// Required.
        /// </param>
        /// <param name='message'>
        /// Required.
        /// </param>
        /// <param name='toTag'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> PostWithOperationResponseAsync(string pns, string message, string toTag, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
