// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Entrata.Model.Requests
{

    public class Attributes
    {

        [JsonProperty("IDType")]
        public string IDType { get; set; }

        [JsonProperty("IDRank")]
        public string IDRank { get; set; }

        [JsonProperty("IDScopeType")]
        public string IDScopeType { get; set; }

        [JsonProperty("Status")]
        public string Status { get; set; }
    }

    public class Identification
    {

        [JsonProperty("@attributes")]
        public Attributes Attributes { get; set; }

        [JsonProperty("IDValue")]
        public int IDValue { get; set; }
    }

    public class LeaseId
    {

        [JsonProperty("Identification")]
        public Identification[] Identification { get; set; }
    }

    public class Attributes2
    {

        [JsonProperty("Id")]
        public string Id { get; set; }
    }

    public class Vehicles
    {

        [JsonProperty("Vehicle")]
        public object Vehicle { get; set; }
    }

    public class Attributes3
    {

        [JsonProperty("AddressType")]
        public string AddressType { get; set; }
    }

    public class CustomerAddress
    {

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("@attributes")]
        public Attributes3 Attributes { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }
    }

    public class CustomerAddresses
    {

        [JsonProperty("CustomerAddress")]
        public CustomerAddress[] CustomerAddress { get; set; }
    }

    public class EmploymentDetail
    {

        [JsonProperty("Company")]
        public string Company { get; set; }

        [JsonProperty("CompanyAddress")]
        public string CompanyAddress { get; set; }

        [JsonProperty("Position")]
        public string Position { get; set; }

        [JsonProperty("Salary")]
        public string Salary { get; set; }

        [JsonProperty("StartDate")]
        public string StartDate { get; set; }

        [JsonProperty("Supervisor")]
        public string Supervisor { get; set; }

        [JsonProperty("SupervisorPhone")]
        public string SupervisorPhone { get; set; }
    }

    public class EmploymentDetails
    {

        [JsonProperty("EmploymentDetail")]
        public EmploymentDetail[] EmploymentDetail { get; set; }
    }

    public class Customer
    {

        [JsonProperty("LeaseId")]
        public LeaseId LeaseId { get; set; }

        [JsonProperty("@attributes")]
        public Attributes2 Attributes { get; set; }

        [JsonProperty("FirstName")]
        public string FirstName { get; set; }

        [JsonProperty("LastName")]
        public string LastName { get; set; }

        [JsonProperty("UnitNumber")]
        public string UnitNumber { get; set; }

        [JsonProperty("BuildingName")]
        public string BuildingName { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("City")]
        public string City { get; set; }

        [JsonProperty("State")]
        public string State { get; set; }

        [JsonProperty("PostalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("MiddleName")]
        public string MiddleName { get; set; }

        [JsonProperty("Vehicles")]
        public Vehicles Vehicles { get; set; }

        [JsonProperty("CustomerAddresses")]
        public CustomerAddresses CustomerAddresses { get; set; }

        [JsonProperty("EmploymentDetails")]
        public EmploymentDetails EmploymentDetails { get; set; }

        [JsonProperty("MaidenName")]
        public string MaidenName { get; set; }
    }

    public class Customers
    {

        [JsonProperty("Customer")]
        public Customer[] Customer { get; set; }
    }

    public class Result
    {

        [JsonProperty("Customers")]
        public Customers Customers { get; set; }
    }

    public class Response
    {

        [JsonProperty("requestId")]
        public string RequestId { get; set; }

        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonProperty("result")]
        public Result Result { get; set; }
    }

    public class GetCustomersResponse
    {

        [JsonProperty("response")]
        public Response Response { get; set; }
    }

}
