//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentApps.Payments.Forte.Forte.Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class Authentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string APILoginIDField;
        
        private string TSHashField;
        
        private string UTCTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string APILoginID {
            get {
                return this.APILoginIDField;
            }
            set {
                if ((object.ReferenceEquals(this.APILoginIDField, value) != true)) {
                    this.APILoginIDField = value;
                    this.RaisePropertyChanged("APILoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TSHash {
            get {
                return this.TSHashField;
            }
            set {
                if ((object.ReferenceEquals(this.TSHashField, value) != true)) {
                    this.TSHashField = value;
                    this.RaisePropertyChanged("TSHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UTCTime {
            get {
                return this.UTCTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UTCTimeField, value) != true)) {
                    this.UTCTimeField = value;
                    this.RaisePropertyChanged("UTCTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientRecord", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class ClientRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MerchantIDField;
        
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiptoFaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsumerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.ClientStatus> StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ShiptoFirstName {
            get {
                return this.ShiptoFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoFirstNameField, value) != true)) {
                    this.ShiptoFirstNameField = value;
                    this.RaisePropertyChanged("ShiptoFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ShiptoLastName {
            get {
                return this.ShiptoLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoLastNameField, value) != true)) {
                    this.ShiptoLastNameField = value;
                    this.RaisePropertyChanged("ShiptoLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string ShiptoCompanyName {
            get {
                return this.ShiptoCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoCompanyNameField, value) != true)) {
                    this.ShiptoCompanyNameField = value;
                    this.RaisePropertyChanged("ShiptoCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ShiptoAddress1 {
            get {
                return this.ShiptoAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoAddress1Field, value) != true)) {
                    this.ShiptoAddress1Field = value;
                    this.RaisePropertyChanged("ShiptoAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string ShiptoAddress2 {
            get {
                return this.ShiptoAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoAddress2Field, value) != true)) {
                    this.ShiptoAddress2Field = value;
                    this.RaisePropertyChanged("ShiptoAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string ShiptoCity {
            get {
                return this.ShiptoCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoCityField, value) != true)) {
                    this.ShiptoCityField = value;
                    this.RaisePropertyChanged("ShiptoCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string ShiptoState {
            get {
                return this.ShiptoStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoStateField, value) != true)) {
                    this.ShiptoStateField = value;
                    this.RaisePropertyChanged("ShiptoState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string ShiptoPostalCode {
            get {
                return this.ShiptoPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoPostalCodeField, value) != true)) {
                    this.ShiptoPostalCodeField = value;
                    this.RaisePropertyChanged("ShiptoPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string ShiptoCountryCode {
            get {
                return this.ShiptoCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoCountryCodeField, value) != true)) {
                    this.ShiptoCountryCodeField = value;
                    this.RaisePropertyChanged("ShiptoCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string ShiptoPhoneNumber {
            get {
                return this.ShiptoPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoPhoneNumberField, value) != true)) {
                    this.ShiptoPhoneNumberField = value;
                    this.RaisePropertyChanged("ShiptoPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string ShiptoFaxNumber {
            get {
                return this.ShiptoFaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiptoFaxNumberField, value) != true)) {
                    this.ShiptoFaxNumberField = value;
                    this.RaisePropertyChanged("ShiptoFaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string ConsumerID {
            get {
                return this.ConsumerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerIDField, value) != true)) {
                    this.ConsumerIDField = value;
                    this.RaisePropertyChanged("ConsumerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.ClientStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientStatus", Namespace="https://ws.paymentsgateway.net/v1")]
    public enum ClientStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethod", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class PaymentMethod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MerchantIDField;
        
        private int ClientIDField;
        
        private int PaymentMethodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AcctHolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.CcCardType> CcCardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CcProcurementCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EcAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EcAccountTRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.EcAccountType> EcAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SuppressAccountUpdaterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int PaymentMethodID {
            get {
                return this.PaymentMethodIDField;
            }
            set {
                if ((this.PaymentMethodIDField.Equals(value) != true)) {
                    this.PaymentMethodIDField = value;
                    this.RaisePropertyChanged("PaymentMethodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string AcctHolderName {
            get {
                return this.AcctHolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AcctHolderNameField, value) != true)) {
                    this.AcctHolderNameField = value;
                    this.RaisePropertyChanged("AcctHolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CcCardNumber {
            get {
                return this.CcCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CcCardNumberField, value) != true)) {
                    this.CcCardNumberField = value;
                    this.RaisePropertyChanged("CcCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CcExpirationDate {
            get {
                return this.CcExpirationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CcExpirationDateField, value) != true)) {
                    this.CcExpirationDateField = value;
                    this.RaisePropertyChanged("CcExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.CcCardType> CcCardType {
            get {
                return this.CcCardTypeField;
            }
            set {
                if ((this.CcCardTypeField.Equals(value) != true)) {
                    this.CcCardTypeField = value;
                    this.RaisePropertyChanged("CcCardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<bool> CcProcurementCard {
            get {
                return this.CcProcurementCardField;
            }
            set {
                if ((this.CcProcurementCardField.Equals(value) != true)) {
                    this.CcProcurementCardField = value;
                    this.RaisePropertyChanged("CcProcurementCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string EcAccountNumber {
            get {
                return this.EcAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EcAccountNumberField, value) != true)) {
                    this.EcAccountNumberField = value;
                    this.RaisePropertyChanged("EcAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string EcAccountTRN {
            get {
                return this.EcAccountTRNField;
            }
            set {
                if ((object.ReferenceEquals(this.EcAccountTRNField, value) != true)) {
                    this.EcAccountTRNField = value;
                    this.RaisePropertyChanged("EcAccountTRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<ApartmentApps.Payments.Forte.Forte.Client.EcAccountType> EcAccountType {
            get {
                return this.EcAccountTypeField;
            }
            set {
                if ((this.EcAccountTypeField.Equals(value) != true)) {
                    this.EcAccountTypeField = value;
                    this.RaisePropertyChanged("EcAccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<bool> SuppressAccountUpdater {
            get {
                return this.SuppressAccountUpdaterField;
            }
            set {
                if ((this.SuppressAccountUpdaterField.Equals(value) != true)) {
                    this.SuppressAccountUpdaterField = value;
                    this.RaisePropertyChanged("SuppressAccountUpdater");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CcCardType", Namespace="https://ws.paymentsgateway.net/v1")]
    public enum CcCardType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VISA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAST = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMER = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DINE = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JCB = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EcAccountType", Namespace="https://ws.paymentsgateway.net/v1")]
    public enum EcAccountType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHECKING = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAVINGS = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.paymentsgateway.net/v1", ConfigurationName="Forte.Client.IClientService")]
    public interface IClientService {
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/createClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/createClientResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.createClientResponse createClient(ApartmentApps.Payments.Forte.Forte.Client.createClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/createClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/createClientResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createClientResponse> createClientAsync(ApartmentApps.Payments.Forte.Forte.Client.createClientRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/updateClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/updateClientResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse updateClient(ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/updateClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/updateClientResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse> updateClientAsync(ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/deleteClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/deleteClientResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse deleteClient(ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/deleteClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/deleteClientResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse> deleteClientAsync(ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/getClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/getClientResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.getClientResponse getClient(ApartmentApps.Payments.Forte.Forte.Client.getClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/getClient", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/getClientResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getClientResponse> getClientAsync(ApartmentApps.Payments.Forte.Forte.Client.getClientRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/createPaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/createPaymentMethodResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse createPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/createPaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/createPaymentMethodResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse> createPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/updatePaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/updatePaymentMethodResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse updatePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/updatePaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/updatePaymentMethodResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse> updatePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/deletePaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/deletePaymentMethodResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse deletePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/deletePaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/deletePaymentMethodResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse> deletePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest request);
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/getPaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/getPaymentMethodResponse")]
        ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse getPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IClientService/getPaymentMethod", ReplyAction="https://ws.paymentsgateway.net/v1/IClientService/getPaymentMethodResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse> getPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createClient", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.createClientRequestBody Body;
        
        public createClientRequest() {
        }
        
        public createClientRequest(ApartmentApps.Payments.Forte.Forte.Client.createClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class createClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client;
        
        public createClientRequestBody() {
        }
        
        public createClientRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            this.ticket = ticket;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createClientResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.createClientResponseBody Body;
        
        public createClientResponse() {
        }
        
        public createClientResponse(ApartmentApps.Payments.Forte.Forte.Client.createClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class createClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createClientResult;
        
        public createClientResponseBody() {
        }
        
        public createClientResponseBody(int createClientResult) {
            this.createClientResult = createClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateClient", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.updateClientRequestBody Body;
        
        public updateClientRequest() {
        }
        
        public updateClientRequest(ApartmentApps.Payments.Forte.Forte.Client.updateClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class updateClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client;
        
        public updateClientRequestBody() {
        }
        
        public updateClientRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            this.ticket = ticket;
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateClientResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.updateClientResponseBody Body;
        
        public updateClientResponse() {
        }
        
        public updateClientResponse(ApartmentApps.Payments.Forte.Forte.Client.updateClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class updateClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateClientResult;
        
        public updateClientResponseBody() {
        }
        
        public updateClientResponseBody(int updateClientResult) {
            this.updateClientResult = updateClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteClient", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequestBody Body;
        
        public deleteClientRequest() {
        }
        
        public deleteClientRequest(ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class deleteClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ClientID;
        
        public deleteClientRequestBody() {
        }
        
        public deleteClientRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            this.ticket = ticket;
            this.MerchantID = MerchantID;
            this.ClientID = ClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteClientResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponseBody Body;
        
        public deleteClientResponse() {
        }
        
        public deleteClientResponse(ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class deleteClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int deleteClientResult;
        
        public deleteClientResponseBody() {
        }
        
        public deleteClientResponseBody(int deleteClientResult) {
            this.deleteClientResult = deleteClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClient", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.getClientRequestBody Body;
        
        public getClientRequest() {
        }
        
        public getClientRequest(ApartmentApps.Payments.Forte.Forte.Client.getClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ClientID;
        
        public getClientRequestBody() {
        }
        
        public getClientRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            this.ticket = ticket;
            this.MerchantID = MerchantID;
            this.ClientID = ClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.getClientResponseBody Body;
        
        public getClientResponse() {
        }
        
        public getClientResponse(ApartmentApps.Payments.Forte.Forte.Client.getClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.ClientRecord[] getClientResult;
        
        public getClientResponseBody() {
        }
        
        public getClientResponseBody(ApartmentApps.Payments.Forte.Forte.Client.ClientRecord[] getClientResult) {
            this.getClientResult = getClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaymentMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPaymentMethod", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequestBody Body;
        
        public createPaymentMethodRequest() {
        }
        
        public createPaymentMethodRequest(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class createPaymentMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment;
        
        public createPaymentMethodRequestBody() {
        }
        
        public createPaymentMethodRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            this.ticket = ticket;
            this.payment = payment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createPaymentMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createPaymentMethodResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponseBody Body;
        
        public createPaymentMethodResponse() {
        }
        
        public createPaymentMethodResponse(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class createPaymentMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createPaymentMethodResult;
        
        public createPaymentMethodResponseBody() {
        }
        
        public createPaymentMethodResponseBody(int createPaymentMethodResult) {
            this.createPaymentMethodResult = createPaymentMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePaymentMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePaymentMethod", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequestBody Body;
        
        public updatePaymentMethodRequest() {
        }
        
        public updatePaymentMethodRequest(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class updatePaymentMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment;
        
        public updatePaymentMethodRequestBody() {
        }
        
        public updatePaymentMethodRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            this.ticket = ticket;
            this.payment = payment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePaymentMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePaymentMethodResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponseBody Body;
        
        public updatePaymentMethodResponse() {
        }
        
        public updatePaymentMethodResponse(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class updatePaymentMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updatePaymentMethodResult;
        
        public updatePaymentMethodResponseBody() {
        }
        
        public updatePaymentMethodResponseBody(int updatePaymentMethodResult) {
            this.updatePaymentMethodResult = updatePaymentMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePaymentMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePaymentMethod", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequestBody Body;
        
        public deletePaymentMethodRequest() {
        }
        
        public deletePaymentMethodRequest(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class deletePaymentMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PaymentMethodID;
        
        public deletePaymentMethodRequestBody() {
        }
        
        public deletePaymentMethodRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int PaymentMethodID) {
            this.ticket = ticket;
            this.MerchantID = MerchantID;
            this.PaymentMethodID = PaymentMethodID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deletePaymentMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deletePaymentMethodResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponseBody Body;
        
        public deletePaymentMethodResponse() {
        }
        
        public deletePaymentMethodResponse(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class deletePaymentMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int deletePaymentMethodResult;
        
        public deletePaymentMethodResponseBody() {
        }
        
        public deletePaymentMethodResponseBody(int deletePaymentMethodResult) {
            this.deletePaymentMethodResult = deletePaymentMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentMethod", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequestBody Body;
        
        public getPaymentMethodRequest() {
        }
        
        public getPaymentMethodRequest(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getPaymentMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ClientID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int PaymentMethodID;
        
        public getPaymentMethodRequestBody() {
        }
        
        public getPaymentMethodRequestBody(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID, int PaymentMethodID) {
            this.ticket = ticket;
            this.MerchantID = MerchantID;
            this.ClientID = ClientID;
            this.PaymentMethodID = PaymentMethodID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentMethodResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponseBody Body;
        
        public getPaymentMethodResponse() {
        }
        
        public getPaymentMethodResponse(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getPaymentMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod[] getPaymentMethodResult;
        
        public getPaymentMethodResponseBody() {
        }
        
        public getPaymentMethodResponseBody(ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod[] getPaymentMethodResult) {
            this.getPaymentMethodResult = getPaymentMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientServiceChannel : ApartmentApps.Payments.Forte.Forte.Client.IClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceClient : System.ServiceModel.ClientBase<ApartmentApps.Payments.Forte.Forte.Client.IClientService>, ApartmentApps.Payments.Forte.Forte.Client.IClientService {
        
        public ClientServiceClient() {
        }
        
        public ClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.createClientResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.createClient(ApartmentApps.Payments.Forte.Forte.Client.createClientRequest request) {
            return base.Channel.createClient(request);
        }
        
        public int createClient(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            ApartmentApps.Payments.Forte.Forte.Client.createClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.createClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.createClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.client = client;
            ApartmentApps.Payments.Forte.Forte.Client.createClientResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).createClient(inValue);
            return retVal.Body.createClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createClientResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.createClientAsync(ApartmentApps.Payments.Forte.Forte.Client.createClientRequest request) {
            return base.Channel.createClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createClientResponse> createClientAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            ApartmentApps.Payments.Forte.Forte.Client.createClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.createClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.createClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.client = client;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).createClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.updateClient(ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest request) {
            return base.Channel.updateClient(request);
        }
        
        public int updateClient(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.updateClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.client = client;
            ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).updateClient(inValue);
            return retVal.Body.updateClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.updateClientAsync(ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest request) {
            return base.Channel.updateClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updateClientResponse> updateClientAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.ClientRecord client) {
            ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.updateClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.updateClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.client = client;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).updateClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.deleteClient(ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest request) {
            return base.Channel.deleteClient(request);
        }
        
        public int deleteClient(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).deleteClient(inValue);
            return retVal.Body.deleteClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.deleteClientAsync(ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest request) {
            return base.Channel.deleteClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deleteClientResponse> deleteClientAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.deleteClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).deleteClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.getClientResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.getClient(ApartmentApps.Payments.Forte.Forte.Client.getClientRequest request) {
            return base.Channel.getClient(request);
        }
        
        public ApartmentApps.Payments.Forte.Forte.Client.ClientRecord[] getClient(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            ApartmentApps.Payments.Forte.Forte.Client.getClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.getClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.getClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            ApartmentApps.Payments.Forte.Forte.Client.getClientResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).getClient(inValue);
            return retVal.Body.getClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getClientResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.getClientAsync(ApartmentApps.Payments.Forte.Forte.Client.getClientRequest request) {
            return base.Channel.getClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getClientResponse> getClientAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID) {
            ApartmentApps.Payments.Forte.Forte.Client.getClientRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.getClientRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.getClientRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).getClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.createPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest request) {
            return base.Channel.createPaymentMethod(request);
        }
        
        public int createPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.payment = payment;
            ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).createPaymentMethod(inValue);
            return retVal.Body.createPaymentMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.createPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest request) {
            return base.Channel.createPaymentMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodResponse> createPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.createPaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.payment = payment;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).createPaymentMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.updatePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest request) {
            return base.Channel.updatePaymentMethod(request);
        }
        
        public int updatePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.payment = payment;
            ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).updatePaymentMethod(inValue);
            return retVal.Body.updatePaymentMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.updatePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest request) {
            return base.Channel.updatePaymentMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodResponse> updatePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod payment) {
            ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.updatePaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.payment = payment;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).updatePaymentMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.deletePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest request) {
            return base.Channel.deletePaymentMethod(request);
        }
        
        public int deletePaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int PaymentMethodID) {
            ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.PaymentMethodID = PaymentMethodID;
            ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).deletePaymentMethod(inValue);
            return retVal.Body.deletePaymentMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.deletePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest request) {
            return base.Channel.deletePaymentMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodResponse> deletePaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int PaymentMethodID) {
            ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.deletePaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.PaymentMethodID = PaymentMethodID;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).deletePaymentMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse ApartmentApps.Payments.Forte.Forte.Client.IClientService.getPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest request) {
            return base.Channel.getPaymentMethod(request);
        }
        
        public ApartmentApps.Payments.Forte.Forte.Client.PaymentMethod[] getPaymentMethod(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID, int PaymentMethodID) {
            ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            inValue.Body.PaymentMethodID = PaymentMethodID;
            ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).getPaymentMethod(inValue);
            return retVal.Body.getPaymentMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse> ApartmentApps.Payments.Forte.Forte.Client.IClientService.getPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest request) {
            return base.Channel.getPaymentMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodResponse> getPaymentMethodAsync(ApartmentApps.Payments.Forte.Forte.Client.Authentication ticket, int MerchantID, int ClientID, int PaymentMethodID) {
            ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest inValue = new ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Client.getPaymentMethodRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.ClientID = ClientID;
            inValue.Body.PaymentMethodID = PaymentMethodID;
            return ((ApartmentApps.Payments.Forte.Forte.Client.IClientService)(this)).getPaymentMethodAsync(inValue);
        }
    }
}
