// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class AddCreditCardBindingModel
    {
        private string _accountHolderName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AccountHolderName
        {
            get { return this._accountHolderName; }
            set { this._accountHolderName = value; }
        }
        
        private string _cardNumber;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CardNumber
        {
            get { return this._cardNumber; }
            set { this._cardNumber = value; }
        }
        
        private int? _cardType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? CardType
        {
            get { return this._cardType; }
            set { this._cardType = value; }
        }
        
        private string _expirationDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ExpirationDate
        {
            get { return this._expirationDate; }
            set { this._expirationDate = value; }
        }
        
        private string _friendlyName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FriendlyName
        {
            get { return this._friendlyName; }
            set { this._friendlyName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AddCreditCardBindingModel class.
        /// </summary>
        public AddCreditCardBindingModel()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type AddCreditCardBindingModel
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AccountHolderName != null)
            {
                outputObject["AccountHolderName"] = this.AccountHolderName;
            }
            if (this.CardNumber != null)
            {
                outputObject["CardNumber"] = this.CardNumber;
            }
            if (this.CardType != null)
            {
                outputObject["CardType"] = this.CardType.Value;
            }
            if (this.ExpirationDate != null)
            {
                outputObject["ExpirationDate"] = this.ExpirationDate;
            }
            if (this.FriendlyName != null)
            {
                outputObject["FriendlyName"] = this.FriendlyName;
            }
            return outputObject;
        }
    }
}
