// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class AddCreditCardResult
    {
        private string _errorMessage;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ErrorMessage
        {
            get { return this._errorMessage; }
            set { this._errorMessage = value; }
        }
        
        private int? _paymentOptionId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? PaymentOptionId
        {
            get { return this._paymentOptionId; }
            set { this._paymentOptionId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AddCreditCardResult class.
        /// </summary>
        public AddCreditCardResult()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken errorMessageValue = inputObject["ErrorMessage"];
                if (errorMessageValue != null && errorMessageValue.Type != JTokenType.Null)
                {
                    this.ErrorMessage = ((string)errorMessageValue);
                }
                JToken paymentOptionIdValue = inputObject["PaymentOptionId"];
                if (paymentOptionIdValue != null && paymentOptionIdValue.Type != JTokenType.Null)
                {
                    this.PaymentOptionId = ((int)paymentOptionIdValue);
                }
            }
        }
    }
}
