// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ApartmentApps.Client.Models;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public static partial class AlertBindingModelCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AlertBindingModel> DeserializeJson(JToken inputObject)
        {
            IList<AlertBindingModel> deserializedObject = new List<AlertBindingModel>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AlertBindingModel alertBindingModel = new AlertBindingModel();
                alertBindingModel.DeserializeJson(iListValue);
                deserializedObject.Add(alertBindingModel);
            }
            return deserializedObject;
        }
    }
}
