// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ApartmentApps.Client.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class CheckinBindingModel
    {
        private string _comments;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Comments
        {
            get { return this._comments; }
            set { this._comments = value; }
        }
        
        private DateTimeOffset? _date;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Date
        {
            get { return this._date; }
            set { this._date = value; }
        }
        
        private IList<ImageReference> _photos;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ImageReference> Photos
        {
            get { return this._photos; }
            set { this._photos = value; }
        }
        
        private string _statusId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string StatusId
        {
            get { return this._statusId; }
            set { this._statusId = value; }
        }
        
        private string _workerName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string WorkerName
        {
            get { return this._workerName; }
            set { this._workerName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CheckinBindingModel class.
        /// </summary>
        public CheckinBindingModel()
        {
            this.Photos = new LazyList<ImageReference>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken commentsValue = inputObject["Comments"];
                if (commentsValue != null && commentsValue.Type != JTokenType.Null)
                {
                    this.Comments = ((string)commentsValue);
                }
                JToken dateValue = inputObject["Date"];
                if (dateValue != null && dateValue.Type != JTokenType.Null)
                {
                    this.Date = ((DateTimeOffset)dateValue);
                }
                JToken photosSequence = ((JToken)inputObject["Photos"]);
                if (photosSequence != null && photosSequence.Type != JTokenType.Null)
                {
                    foreach (JToken photosValue in ((JArray)photosSequence))
                    {
                        ImageReference imageReference = new ImageReference();
                        imageReference.DeserializeJson(photosValue);
                        this.Photos.Add(imageReference);
                    }
                }
                JToken statusIdValue = inputObject["StatusId"];
                if (statusIdValue != null && statusIdValue.Type != JTokenType.Null)
                {
                    this.StatusId = ((string)statusIdValue);
                }
                JToken workerNameValue = inputObject["WorkerName"];
                if (workerNameValue != null && workerNameValue.Type != JTokenType.Null)
                {
                    this.WorkerName = ((string)workerNameValue);
                }
            }
        }
    }
}
