// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class CourtesyCheckinBindingModel
    {
        private IList<string> _acceptableCheckinCodes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> AcceptableCheckinCodes
        {
            get { return this._acceptableCheckinCodes; }
            set { this._acceptableCheckinCodes = value; }
        }
        
        private bool? _complete;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Complete
        {
            get { return this._complete; }
            set { this._complete = value; }
        }
        
        private DateTimeOffset? _date;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Date
        {
            get { return this._date; }
            set { this._date = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _label;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Label
        {
            get { return this._label; }
            set { this._label = value; }
        }
        
        private double? _latitude;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Latitude
        {
            get { return this._latitude; }
            set { this._latitude = value; }
        }
        
        private double? _longitude;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Longitude
        {
            get { return this._longitude; }
            set { this._longitude = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CourtesyCheckinBindingModel class.
        /// </summary>
        public CourtesyCheckinBindingModel()
        {
            this.AcceptableCheckinCodes = new LazyList<string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken acceptableCheckinCodesSequence = ((JToken)inputObject["AcceptableCheckinCodes"]);
                if (acceptableCheckinCodesSequence != null && acceptableCheckinCodesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken acceptableCheckinCodesValue in ((JArray)acceptableCheckinCodesSequence))
                    {
                        this.AcceptableCheckinCodes.Add(((string)acceptableCheckinCodesValue));
                    }
                }
                JToken completeValue = inputObject["Complete"];
                if (completeValue != null && completeValue.Type != JTokenType.Null)
                {
                    this.Complete = ((bool)completeValue);
                }
                JToken dateValue = inputObject["Date"];
                if (dateValue != null && dateValue.Type != JTokenType.Null)
                {
                    this.Date = ((DateTimeOffset)dateValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken labelValue = inputObject["Label"];
                if (labelValue != null && labelValue.Type != JTokenType.Null)
                {
                    this.Label = ((string)labelValue);
                }
                JToken latitudeValue = inputObject["Latitude"];
                if (latitudeValue != null && latitudeValue.Type != JTokenType.Null)
                {
                    this.Latitude = ((double)latitudeValue);
                }
                JToken longitudeValue = inputObject["Longitude"];
                if (longitudeValue != null && longitudeValue.Type != JTokenType.Null)
                {
                    this.Longitude = ((double)longitudeValue);
                }
            }
        }
    }
}
