// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using ApartmentApps.Client.Models;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class IncidentIndexBindingModel
    {
        private string _buildingName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BuildingName
        {
            get { return this._buildingName; }
            set { this._buildingName = value; }
        }
        
        private string _comments;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Comments
        {
            get { return this._comments; }
            set { this._comments = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private IncidentCheckinBindingModel _latestCheckin;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IncidentCheckinBindingModel LatestCheckin
        {
            get { return this._latestCheckin; }
            set { this._latestCheckin = value; }
        }
        
        private UserBindingModel _reportedBy;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public UserBindingModel ReportedBy
        {
            get { return this._reportedBy; }
            set { this._reportedBy = value; }
        }
        
        private string _reporter;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Reporter
        {
            get { return this._reporter; }
            set { this._reporter = value; }
        }
        
        private DateTimeOffset? _requestDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? RequestDate
        {
            get { return this._requestDate; }
            set { this._requestDate = value; }
        }
        
        private string _statusId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string StatusId
        {
            get { return this._statusId; }
            set { this._statusId = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        private string _unitName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UnitName
        {
            get { return this._unitName; }
            set { this._unitName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IncidentIndexBindingModel class.
        /// </summary>
        public IncidentIndexBindingModel()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken buildingNameValue = inputObject["BuildingName"];
                if (buildingNameValue != null && buildingNameValue.Type != JTokenType.Null)
                {
                    this.BuildingName = ((string)buildingNameValue);
                }
                JToken commentsValue = inputObject["Comments"];
                if (commentsValue != null && commentsValue.Type != JTokenType.Null)
                {
                    this.Comments = ((string)commentsValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = idValue.ToString(Newtonsoft.Json.Formatting.Indented);
                }
                JToken latestCheckinValue = inputObject["LatestCheckin"];
                if (latestCheckinValue != null && latestCheckinValue.Type != JTokenType.Null)
                {
                    IncidentCheckinBindingModel incidentCheckinBindingModel = new IncidentCheckinBindingModel();
                    incidentCheckinBindingModel.DeserializeJson(latestCheckinValue);
                    this.LatestCheckin = incidentCheckinBindingModel;
                }
                JToken reportedByValue = inputObject["ReportedBy"];
                if (reportedByValue != null && reportedByValue.Type != JTokenType.Null)
                {
                    UserBindingModel userBindingModel = new UserBindingModel();
                    userBindingModel.DeserializeJson(reportedByValue);
                    this.ReportedBy = userBindingModel;
                }
                JToken reporterValue = inputObject["Reporter"];
                if (reporterValue != null && reporterValue.Type != JTokenType.Null)
                {
                    this.Reporter = ((string)reporterValue);
                }
                JToken requestDateValue = inputObject["RequestDate"];
                if (requestDateValue != null && requestDateValue.Type != JTokenType.Null)
                {
                    this.RequestDate = ((DateTimeOffset)requestDateValue);
                }
                JToken statusIdValue = inputObject["StatusId"];
                if (statusIdValue != null && statusIdValue.Type != JTokenType.Null)
                {
                    this.StatusId = ((string)statusIdValue);
                }
                JToken titleValue = inputObject["Title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
                JToken unitNameValue = inputObject["UnitName"];
                if (unitNameValue != null && unitNameValue.Type != JTokenType.Null)
                {
                    this.UnitName = ((string)unitNameValue);
                }
            }
        }
    }
}
