// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ApartmentApps.Client.Models;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public static partial class LocationBindingModelCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<LocationBindingModel> DeserializeJson(JToken inputObject)
        {
            IList<LocationBindingModel> deserializedObject = new List<LocationBindingModel>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                LocationBindingModel locationBindingModel = new LocationBindingModel();
                locationBindingModel.DeserializeJson(iListValue);
                deserializedObject.Add(locationBindingModel);
            }
            return deserializedObject;
        }
    }
}
