// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class LookupPairModel
    {
        private string _key;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Key
        {
            get { return this._key; }
            set { this._key = value; }
        }
        
        private string _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the LookupPairModel class.
        /// </summary>
        public LookupPairModel()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken keyValue = inputObject["Key"];
                if (keyValue != null && keyValue.Type != JTokenType.Null)
                {
                    this.Key = ((string)keyValue);
                }
                JToken valueValue = inputObject["Value"];
                if (valueValue != null && valueValue.Type != JTokenType.Null)
                {
                    this.Value = ((string)valueValue);
                }
            }
        }
    }
}
