// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class PaymentLineBindingModel
    {
        private int? _format;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Format
        {
            get { return this._format; }
            set { this._format = value; }
        }
        
        private string _price;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the PaymentLineBindingModel class.
        /// </summary>
        public PaymentLineBindingModel()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken formatValue = inputObject["Format"];
                if (formatValue != null && formatValue.Type != JTokenType.Null)
                {
                    this.Format = ((int)formatValue);
                }
                JToken priceValue = inputObject["Price"];
                if (priceValue != null && priceValue.Type != JTokenType.Null)
                {
                    this.Price = ((string)priceValue);
                }
                JToken titleValue = inputObject["Title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
            }
        }
    }
}
