// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class ScanIdResult
    {
        private string _addressLine1;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AddressLine1
        {
            get { return this._addressLine1; }
            set { this._addressLine1 = value; }
        }
        
        private string _addressLine2;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AddressLine2
        {
            get { return this._addressLine2; }
            set { this._addressLine2 = value; }
        }
        
        private DateTimeOffset? _birthdate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? Birthdate
        {
            get { return this._birthdate; }
            set { this._birthdate = value; }
        }
        
        private DateTimeOffset? _cardRevisionDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? CardRevisionDate
        {
            get { return this._cardRevisionDate; }
            set { this._cardRevisionDate = value; }
        }
        
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _classificationCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ClassificationCode
        {
            get { return this._classificationCode; }
            set { this._classificationCode = value; }
        }
        
        private string _complianceType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ComplianceType
        {
            get { return this._complianceType; }
            set { this._complianceType = value; }
        }
        
        private string _country;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Country
        {
            get { return this._country; }
            set { this._country = value; }
        }
        
        private string _countryCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CountryCode
        {
            get { return this._countryCode; }
            set { this._countryCode = value; }
        }
        
        private string _endorsementCodeDescription;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string EndorsementCodeDescription
        {
            get { return this._endorsementCodeDescription; }
            set { this._endorsementCodeDescription = value; }
        }
        
        private string _endorsementsCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string EndorsementsCode
        {
            get { return this._endorsementsCode; }
            set { this._endorsementsCode = value; }
        }
        
        private DateTimeOffset? _expirationDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ExpirationDate
        {
            get { return this._expirationDate; }
            set { this._expirationDate = value; }
        }
        
        private string _eyeColor;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string EyeColor
        {
            get { return this._eyeColor; }
            set { this._eyeColor = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private string _fullName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FullName
        {
            get { return this._fullName; }
            set { this._fullName = value; }
        }
        
        private string _gender;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Gender
        {
            get { return this._gender; }
            set { this._gender = value; }
        }
        
        private string _hairColor;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string HairColor
        {
            get { return this._hairColor; }
            set { this._hairColor = value; }
        }
        
        private DateTimeOffset? _issueDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? IssueDate
        {
            get { return this._issueDate; }
            set { this._issueDate = value; }
        }
        
        private string _issuedBy;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string IssuedBy
        {
            get { return this._issuedBy; }
            set { this._issuedBy = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private string _postalCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PostalCode
        {
            get { return this._postalCode; }
            set { this._postalCode = value; }
        }
        
        private string _race;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Race
        {
            get { return this._race; }
            set { this._race = value; }
        }
        
        private string _vehicleClassCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string VehicleClassCode
        {
            get { return this._vehicleClassCode; }
            set { this._vehicleClassCode = value; }
        }
        
        private string _vehicleClassCodeDescription;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string VehicleClassCodeDescription
        {
            get { return this._vehicleClassCodeDescription; }
            set { this._vehicleClassCodeDescription = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ScanIdResult class.
        /// </summary>
        public ScanIdResult()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken addressLine1Value = inputObject["AddressLine1"];
                if (addressLine1Value != null && addressLine1Value.Type != JTokenType.Null)
                {
                    this.AddressLine1 = ((string)addressLine1Value);
                }
                JToken addressLine2Value = inputObject["AddressLine2"];
                if (addressLine2Value != null && addressLine2Value.Type != JTokenType.Null)
                {
                    this.AddressLine2 = ((string)addressLine2Value);
                }
                JToken birthdateValue = inputObject["Birthdate"];
                if (birthdateValue != null && birthdateValue.Type != JTokenType.Null)
                {
                    this.Birthdate = ((DateTimeOffset)birthdateValue);
                }
                JToken cardRevisionDateValue = inputObject["CardRevisionDate"];
                if (cardRevisionDateValue != null && cardRevisionDateValue.Type != JTokenType.Null)
                {
                    this.CardRevisionDate = ((DateTimeOffset)cardRevisionDateValue);
                }
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken classificationCodeValue = inputObject["ClassificationCode"];
                if (classificationCodeValue != null && classificationCodeValue.Type != JTokenType.Null)
                {
                    this.ClassificationCode = ((string)classificationCodeValue);
                }
                JToken complianceTypeValue = inputObject["ComplianceType"];
                if (complianceTypeValue != null && complianceTypeValue.Type != JTokenType.Null)
                {
                    this.ComplianceType = ((string)complianceTypeValue);
                }
                JToken countryValue = inputObject["Country"];
                if (countryValue != null && countryValue.Type != JTokenType.Null)
                {
                    this.Country = ((string)countryValue);
                }
                JToken countryCodeValue = inputObject["CountryCode"];
                if (countryCodeValue != null && countryCodeValue.Type != JTokenType.Null)
                {
                    this.CountryCode = ((string)countryCodeValue);
                }
                JToken endorsementCodeDescriptionValue = inputObject["EndorsementCodeDescription"];
                if (endorsementCodeDescriptionValue != null && endorsementCodeDescriptionValue.Type != JTokenType.Null)
                {
                    this.EndorsementCodeDescription = ((string)endorsementCodeDescriptionValue);
                }
                JToken endorsementsCodeValue = inputObject["EndorsementsCode"];
                if (endorsementsCodeValue != null && endorsementsCodeValue.Type != JTokenType.Null)
                {
                    this.EndorsementsCode = ((string)endorsementsCodeValue);
                }
                JToken expirationDateValue = inputObject["ExpirationDate"];
                if (expirationDateValue != null && expirationDateValue.Type != JTokenType.Null)
                {
                    this.ExpirationDate = ((DateTimeOffset)expirationDateValue);
                }
                JToken eyeColorValue = inputObject["EyeColor"];
                if (eyeColorValue != null && eyeColorValue.Type != JTokenType.Null)
                {
                    this.EyeColor = ((string)eyeColorValue);
                }
                JToken firstNameValue = inputObject["FirstName"];
                if (firstNameValue != null && firstNameValue.Type != JTokenType.Null)
                {
                    this.FirstName = ((string)firstNameValue);
                }
                JToken fullNameValue = inputObject["FullName"];
                if (fullNameValue != null && fullNameValue.Type != JTokenType.Null)
                {
                    this.FullName = ((string)fullNameValue);
                }
                JToken genderValue = inputObject["Gender"];
                if (genderValue != null && genderValue.Type != JTokenType.Null)
                {
                    this.Gender = ((string)genderValue);
                }
                JToken hairColorValue = inputObject["HairColor"];
                if (hairColorValue != null && hairColorValue.Type != JTokenType.Null)
                {
                    this.HairColor = ((string)hairColorValue);
                }
                JToken issueDateValue = inputObject["IssueDate"];
                if (issueDateValue != null && issueDateValue.Type != JTokenType.Null)
                {
                    this.IssueDate = ((DateTimeOffset)issueDateValue);
                }
                JToken issuedByValue = inputObject["IssuedBy"];
                if (issuedByValue != null && issuedByValue.Type != JTokenType.Null)
                {
                    this.IssuedBy = ((string)issuedByValue);
                }
                JToken lastNameValue = inputObject["LastName"];
                if (lastNameValue != null && lastNameValue.Type != JTokenType.Null)
                {
                    this.LastName = ((string)lastNameValue);
                }
                JToken postalCodeValue = inputObject["PostalCode"];
                if (postalCodeValue != null && postalCodeValue.Type != JTokenType.Null)
                {
                    this.PostalCode = ((string)postalCodeValue);
                }
                JToken raceValue = inputObject["Race"];
                if (raceValue != null && raceValue.Type != JTokenType.Null)
                {
                    this.Race = ((string)raceValue);
                }
                JToken vehicleClassCodeValue = inputObject["VehicleClassCode"];
                if (vehicleClassCodeValue != null && vehicleClassCodeValue.Type != JTokenType.Null)
                {
                    this.VehicleClassCode = ((string)vehicleClassCodeValue);
                }
                JToken vehicleClassCodeDescriptionValue = inputObject["VehicleClassCodeDescription"];
                if (vehicleClassCodeDescriptionValue != null && vehicleClassCodeDescriptionValue.Type != JTokenType.Null)
                {
                    this.VehicleClassCodeDescription = ((string)vehicleClassCodeDescriptionValue);
                }
            }
        }
    }
}
