// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ApartmentApps.Client.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class UserBindingModel
    {
        private IList<ActionLinkModel> _actionLinks;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ActionLinkModel> ActionLinks
        {
            get { return this._actionLinks; }
            set { this._actionLinks = value; }
        }
        
        private string _address;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set { this._address = value; }
        }
        
        private bool? _archived;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? Archived
        {
            get { return this._archived; }
            set { this._archived = value; }
        }
        
        private string _buildingName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BuildingName
        {
            get { return this._buildingName; }
            set { this._buildingName = value; }
        }
        
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _email;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Email
        {
            get { return this._email; }
            set { this._email = value; }
        }
        
        private string _firstName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FirstName
        {
            get { return this._firstName; }
            set { this._firstName = value; }
        }
        
        private string _fullName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string FullName
        {
            get { return this._fullName; }
            set { this._fullName = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _imageThumbnailUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ImageThumbnailUrl
        {
            get { return this._imageThumbnailUrl; }
            set { this._imageThumbnailUrl = value; }
        }
        
        private string _imageUrl;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ImageUrl
        {
            get { return this._imageUrl; }
            set { this._imageUrl = value; }
        }
        
        private bool? _isTenant;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsTenant
        {
            get { return this._isTenant; }
            set { this._isTenant = value; }
        }
        
        private string _lastName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LastName
        {
            get { return this._lastName; }
            set { this._lastName = value; }
        }
        
        private string _phoneNumber;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PhoneNumber
        {
            get { return this._phoneNumber; }
            set { this._phoneNumber = value; }
        }
        
        private string _postalCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PostalCode
        {
            get { return this._postalCode; }
            set { this._postalCode = value; }
        }
        
        private IList<string> _roles;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> Roles
        {
            get { return this._roles; }
            set { this._roles = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        private string _unitName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string UnitName
        {
            get { return this._unitName; }
            set { this._unitName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserBindingModel class.
        /// </summary>
        public UserBindingModel()
        {
            this.ActionLinks = new LazyList<ActionLinkModel>();
            this.Roles = new LazyList<string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken actionLinksSequence = ((JToken)inputObject["ActionLinks"]);
                if (actionLinksSequence != null && actionLinksSequence.Type != JTokenType.Null)
                {
                    foreach (JToken actionLinksValue in ((JArray)actionLinksSequence))
                    {
                        ActionLinkModel actionLinkModel = new ActionLinkModel();
                        actionLinkModel.DeserializeJson(actionLinksValue);
                        this.ActionLinks.Add(actionLinkModel);
                    }
                }
                JToken addressValue = inputObject["Address"];
                if (addressValue != null && addressValue.Type != JTokenType.Null)
                {
                    this.Address = ((string)addressValue);
                }
                JToken archivedValue = inputObject["Archived"];
                if (archivedValue != null && archivedValue.Type != JTokenType.Null)
                {
                    this.Archived = ((bool)archivedValue);
                }
                JToken buildingNameValue = inputObject["BuildingName"];
                if (buildingNameValue != null && buildingNameValue.Type != JTokenType.Null)
                {
                    this.BuildingName = ((string)buildingNameValue);
                }
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken emailValue = inputObject["Email"];
                if (emailValue != null && emailValue.Type != JTokenType.Null)
                {
                    this.Email = ((string)emailValue);
                }
                JToken firstNameValue = inputObject["FirstName"];
                if (firstNameValue != null && firstNameValue.Type != JTokenType.Null)
                {
                    this.FirstName = ((string)firstNameValue);
                }
                JToken fullNameValue = inputObject["FullName"];
                if (fullNameValue != null && fullNameValue.Type != JTokenType.Null)
                {
                    this.FullName = ((string)fullNameValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken imageThumbnailUrlValue = inputObject["ImageThumbnailUrl"];
                if (imageThumbnailUrlValue != null && imageThumbnailUrlValue.Type != JTokenType.Null)
                {
                    this.ImageThumbnailUrl = ((string)imageThumbnailUrlValue);
                }
                JToken imageUrlValue = inputObject["ImageUrl"];
                if (imageUrlValue != null && imageUrlValue.Type != JTokenType.Null)
                {
                    this.ImageUrl = ((string)imageUrlValue);
                }
                JToken isTenantValue = inputObject["IsTenant"];
                if (isTenantValue != null && isTenantValue.Type != JTokenType.Null)
                {
                    this.IsTenant = ((bool)isTenantValue);
                }
                JToken lastNameValue = inputObject["LastName"];
                if (lastNameValue != null && lastNameValue.Type != JTokenType.Null)
                {
                    this.LastName = ((string)lastNameValue);
                }
                JToken phoneNumberValue = inputObject["PhoneNumber"];
                if (phoneNumberValue != null && phoneNumberValue.Type != JTokenType.Null)
                {
                    this.PhoneNumber = ((string)phoneNumberValue);
                }
                JToken postalCodeValue = inputObject["PostalCode"];
                if (postalCodeValue != null && postalCodeValue.Type != JTokenType.Null)
                {
                    this.PostalCode = ((string)postalCodeValue);
                }
                JToken rolesSequence = ((JToken)inputObject["Roles"]);
                if (rolesSequence != null && rolesSequence.Type != JTokenType.Null)
                {
                    foreach (JToken rolesValue in ((JArray)rolesSequence))
                    {
                        this.Roles.Add(((string)rolesValue));
                    }
                }
                JToken titleValue = inputObject["Title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
                JToken unitNameValue = inputObject["UnitName"];
                if (unitNameValue != null && unitNameValue.Type != JTokenType.Null)
                {
                    this.UnitName = ((string)unitNameValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type UserBindingModel
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray actionLinksSequence = null;
            if (this.ActionLinks != null)
            {
                if (this.ActionLinks is ILazyCollection<ActionLinkModel> == false || ((ILazyCollection<ActionLinkModel>)this.ActionLinks).IsInitialized)
                {
                    actionLinksSequence = new JArray();
                    outputObject["ActionLinks"] = actionLinksSequence;
                    foreach (ActionLinkModel actionLinksItem in this.ActionLinks)
                    {
                        if (actionLinksItem != null)
                        {
                            actionLinksSequence.Add(actionLinksItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Address != null)
            {
                outputObject["Address"] = this.Address;
            }
            if (this.Archived != null)
            {
                outputObject["Archived"] = this.Archived.Value;
            }
            if (this.BuildingName != null)
            {
                outputObject["BuildingName"] = this.BuildingName;
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.Email != null)
            {
                outputObject["Email"] = this.Email;
            }
            if (this.FirstName != null)
            {
                outputObject["FirstName"] = this.FirstName;
            }
            if (this.FullName != null)
            {
                outputObject["FullName"] = this.FullName;
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.ImageThumbnailUrl != null)
            {
                outputObject["ImageThumbnailUrl"] = this.ImageThumbnailUrl;
            }
            if (this.ImageUrl != null)
            {
                outputObject["ImageUrl"] = this.ImageUrl;
            }
            if (this.IsTenant != null)
            {
                outputObject["IsTenant"] = this.IsTenant.Value;
            }
            if (this.LastName != null)
            {
                outputObject["LastName"] = this.LastName;
            }
            if (this.PhoneNumber != null)
            {
                outputObject["PhoneNumber"] = this.PhoneNumber;
            }
            if (this.PostalCode != null)
            {
                outputObject["PostalCode"] = this.PostalCode;
            }
            JArray rolesSequence = null;
            if (this.Roles != null)
            {
                if (this.Roles is ILazyCollection<string> == false || ((ILazyCollection<string>)this.Roles).IsInitialized)
                {
                    rolesSequence = new JArray();
                    outputObject["Roles"] = rolesSequence;
                    foreach (string rolesItem in this.Roles)
                    {
                        if (rolesItem != null)
                        {
                            rolesSequence.Add(rolesItem);
                        }
                    }
                }
            }
            if (this.Title != null)
            {
                outputObject["Title"] = this.Title;
            }
            if (this.UnitName != null)
            {
                outputObject["UnitName"] = this.UnitName;
            }
            return outputObject;
        }
    }
}
