// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ApartmentApps.Client.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace ApartmentApps.Client.Models
{
    public partial class UserLookupBindingModel
    {
        private IList<ActionLinkModel> _actionLinks;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ActionLinkModel> ActionLinks
        {
            get { return this._actionLinks; }
            set { this._actionLinks = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UserLookupBindingModel class.
        /// </summary>
        public UserLookupBindingModel()
        {
            this.ActionLinks = new LazyList<ActionLinkModel>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type UserLookupBindingModel
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray actionLinksSequence = null;
            if (this.ActionLinks != null)
            {
                if (this.ActionLinks is ILazyCollection<ActionLinkModel> == false || ((ILazyCollection<ActionLinkModel>)this.ActionLinks).IsInitialized)
                {
                    actionLinksSequence = new JArray();
                    outputObject["ActionLinks"] = actionLinksSequence;
                    foreach (ActionLinkModel actionLinksItem in this.ActionLinks)
                    {
                        if (actionLinksItem != null)
                        {
                            actionLinksSequence.Add(actionLinksItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Id != null)
            {
                outputObject["Id"] = this.Id;
            }
            if (this.Title != null)
            {
                outputObject["Title"] = this.Title;
            }
            return outputObject;
        }
    }
}
