//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmentApps.Payments.Forte.Forte.Merchant {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class Authentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string APILoginIDField;
        
        private string TSHashField;
        
        private string UTCTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string APILoginID {
            get {
                return this.APILoginIDField;
            }
            set {
                if ((object.ReferenceEquals(this.APILoginIDField, value) != true)) {
                    this.APILoginIDField = value;
                    this.RaisePropertyChanged("APILoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TSHash {
            get {
                return this.TSHashField;
            }
            set {
                if ((object.ReferenceEquals(this.TSHashField, value) != true)) {
                    this.TSHashField = value;
                    this.RaisePropertyChanged("TSHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UTCTime {
            get {
                return this.UTCTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.UTCTimeField, value) != true)) {
                    this.UTCTimeField = value;
                    this.RaisePropertyChanged("UTCTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hierarchy", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class Hierarchy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ApartmentApps.Payments.Forte.Forte.Merchant.Folder FolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.Folder Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class Folder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentApps.Payments.Forte.Forte.Merchant.Folder[] FoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ApartmentApps.Payments.Forte.Forte.Merchant.Merchant[] MerchantsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int HID {
            get {
                return this.HIDField;
            }
            set {
                if ((this.HIDField.Equals(value) != true)) {
                    this.HIDField = value;
                    this.RaisePropertyChanged("HID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.Folder[] Folders {
            get {
                return this.FoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.FoldersField, value) != true)) {
                    this.FoldersField = value;
                    this.RaisePropertyChanged("Folders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.Merchant[] Merchants {
            get {
                return this.MerchantsField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantsField, value) != true)) {
                    this.MerchantsField = value;
                    this.RaisePropertyChanged("Merchants");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merchant", Namespace="https://ws.paymentsgateway.net/v1")]
    [System.SerializableAttribute()]
    public partial class Merchant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.paymentsgateway.net/v1", ConfigurationName="Forte.Merchant.IMerchantService")]
    public interface IMerchantService {
        
        // CODEGEN: Generating message contract since element name ticket from namespace https://ws.paymentsgateway.net/v1 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IMerchantService/getHierarchyTree", ReplyAction="https://ws.paymentsgateway.net/v1/IMerchantService/getHierarchyTreeResponse")]
        ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse getHierarchyTree(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.paymentsgateway.net/v1/IMerchantService/getHierarchyTree", ReplyAction="https://ws.paymentsgateway.net/v1/IMerchantService/getHierarchyTreeResponse")]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse> getHierarchyTreeAsync(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHierarchyTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHierarchyTree", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequestBody Body;
        
        public getHierarchyTreeRequest() {
        }
        
        public getHierarchyTreeRequest(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getHierarchyTreeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.Authentication ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MerchantID;
        
        public getHierarchyTreeRequestBody() {
        }
        
        public getHierarchyTreeRequestBody(ApartmentApps.Payments.Forte.Forte.Merchant.Authentication ticket, int MerchantID) {
            this.ticket = ticket;
            this.MerchantID = MerchantID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHierarchyTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHierarchyTreeResponse", Namespace="https://ws.paymentsgateway.net/v1", Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponseBody Body;
        
        public getHierarchyTreeResponse() {
        }
        
        public getHierarchyTreeResponse(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.paymentsgateway.net/v1")]
    public partial class getHierarchyTreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public ApartmentApps.Payments.Forte.Forte.Merchant.Hierarchy getHierarchyTreeResult;
        
        public getHierarchyTreeResponseBody() {
        }
        
        public getHierarchyTreeResponseBody(ApartmentApps.Payments.Forte.Forte.Merchant.Hierarchy getHierarchyTreeResult) {
            this.getHierarchyTreeResult = getHierarchyTreeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMerchantServiceChannel : ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MerchantServiceClient : System.ServiceModel.ClientBase<ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService>, ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService {
        
        public MerchantServiceClient() {
        }
        
        public MerchantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MerchantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerchantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService.getHierarchyTree(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest request) {
            return base.Channel.getHierarchyTree(request);
        }
        
        public ApartmentApps.Payments.Forte.Forte.Merchant.Hierarchy getHierarchyTree(ApartmentApps.Payments.Forte.Forte.Merchant.Authentication ticket, int MerchantID) {
            ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest inValue = new ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse retVal = ((ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService)(this)).getHierarchyTree(inValue);
            return retVal.Body.getHierarchyTreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse> ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService.getHierarchyTreeAsync(ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest request) {
            return base.Channel.getHierarchyTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeResponse> getHierarchyTreeAsync(ApartmentApps.Payments.Forte.Forte.Merchant.Authentication ticket, int MerchantID) {
            ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest inValue = new ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequest();
            inValue.Body = new ApartmentApps.Payments.Forte.Forte.Merchant.getHierarchyTreeRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.MerchantID = MerchantID;
            return ((ApartmentApps.Payments.Forte.Forte.Merchant.IMerchantService)(this)).getHierarchyTreeAsync(inValue);
        }
    }
}
