#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ResidentAppCross.Droid.Resource", IsApplication=true)]

namespace ResidentAppCross.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int LoginScreenFormIconSize = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int LoginScreenFormTextSize = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AppartmentAppsIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Border1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_login_50893_0013_forma = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iconelse = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LOGIN = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LoginButton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo_03 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int monoandroidsplash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int SecurityIcon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int UsernameIcon = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int FlyOutContent = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int FlyOutMenu = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int MenuButton = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040011
			public const int PasswordInput = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int UsernameInput = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int button1 = 2130968594;
			
			// aapt resource value: 0x7f040003
			public const int frameLayout1 = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int horizontalScrollView1 = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int imageView1 = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int imageView2 = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int linearLayout1 = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int linearLayout2 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int linearLayout3 = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int relativeLayout1 = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int textView1 = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int textView2 = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int textView3 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int textView4 = 2130968596;
			
			// aapt resource value: 0x7f040002
			public const int view1 = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int view2 = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContentLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HomeMenuViewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginViewLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuViewLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
