// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ApartmentApps.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201602060345380_RefChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
